package clinicmanagementsystem;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Module1 extends javax.swing.JFrame {
    
    public Module1() {
        initComponents();
        setExtendedState(getExtendedState() | Module1.MAXIMIZED_BOTH);
        showDate();
        showTime();
    }
        void showDate()
        {
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            datelab.setText(s.format(d));
        }
        
        void showTime()
        {
            new Timer(0,new ActionListener()
            {
                public void actionPerformed(ActionEvent e)
                {
                    Date d = new Date();
                    SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                    timelab.setText(s.format(d));
                    
                }
            }).start();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        icn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ema = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        gn = new javax.swing.JComboBox<>();
        Gender = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ill = new javax.swing.JComboBox<>();
        Ill = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        allergy = new javax.swing.JComboBox<>();
        Allergy = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        datelab = new javax.swing.JLabel();
        timelab = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Form");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Patient Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 140, 204, 43);

        jLabel2.setText("                                          Dear Patient, please fill out the form with your details.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 210, 490, 14);

        jLabel3.setText("                      Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 250, 110, 20);
        getContentPane().add(fn);
        fn.setBounds(530, 250, 359, 30);

        jLabel4.setText("          Age   : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(442, 285, 70, 30);
        getContentPane().add(age);
        age.setBounds(530, 288, 359, 30);

        jLabel5.setText("     IC NO.   :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(442, 323, 70, 30);
        getContentPane().add(icn);
        icn.setBounds(530, 326, 359, 30);

        jLabel6.setText("                                       Email  :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(352, 361, 160, 30);
        getContentPane().add(ema);
        ema.setBounds(530, 364, 359, 30);

        jLabel7.setText("                      Phone No :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(382, 399, 130, 30);
        getContentPane().add(cn);
        cn.setBounds(530, 402, 359, 30);

        jLabel8.setText("                 Gender:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 440, 110, 30);

        gn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        getContentPane().add(gn);
        gn.setBounds(530, 440, 149, 30);
        getContentPane().add(Gender);
        Gender.setBounds(685, 440, 204, 30);

        jLabel9.setText("               Illness:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 480, 100, 30);

        ill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allergies", "Colds and Flu", "Conjunctivitis (\"pink eye\")", "Diarrhea", "Headaches", "Mononucleosis", "Stomach aches" }));
        getContentPane().add(ill);
        ill.setBounds(530, 481, 149, 30);
        getContentPane().add(Ill);
        Ill.setBounds(685, 481, 204, 30);

        jLabel10.setText("                                              Allergic to medication :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(252, 519, 270, 30);

        allergy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " " }));
        getContentPane().add(allergy);
        allergy.setBounds(530, 519, 149, 30);
        getContentPane().add(Allergy);
        Allergy.setBounds(685, 519, 204, 30);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(799, 567, 90, 23);

        datelab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        datelab.setText("Date :");
        getContentPane().add(datelab);
        datelab.setBounds(212, 93, 139, 15);

        timelab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        timelab.setText("Time :");
        getContentPane().add(timelab);
        timelab.setBounds(1063, 93, 146, 15);

        jLabel13.setText("<<Go back");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(670, 70, 90, 14);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\swampbckgrnd.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1370, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Fname = fn.getText();
        String Age = age.getText();
        String Icnum = icn.getText();
        String Email = ema.getText();
        String Cnum = cn.getText();
        
        Gender.setText(gn.getSelectedItem().toString());
        Ill.setText(ill.getSelectedItem().toString());
        Allergy.setText(allergy.getSelectedItem().toString());
        
        JOptionPane.showMessageDialog(rootPane,"Thank You for registering, your details have been recorded!"+
        "\nHere are the summary of your Registrations:"+"\nFull name :"+fn.getText()+"\nAge :"+age.getText()+
        "\nIC No. :"+icn.getText()+"\nEmail :"+ema.getText()+"\nContact No. :"+cn.getText()+"\nGender :"+
        gn.getSelectedItem().toString()+"\nIllness :"+ill.getSelectedItem().toString()+"\nAllergy :"+
        allergy.getSelectedItem().toString()+"\n\n"+"\nNote :"+ "\nPlease verify your details before submitting, your appointment"+
        "\nmight be cancelled if your phone number and identification card "+"\nare invalid. Due to the season of Covid-19,Patients"
        +"\n are required to wear facemask before entering the clinic."+"\nStay safe and stay healthy.");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        
        MenuPage obj = new MenuPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Module1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Module1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Module1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Module1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Module1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Allergy;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField Ill;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox<String> allergy;
    private javax.swing.JTextField cn;
    private javax.swing.JLabel datelab;
    private javax.swing.JTextField ema;
    private javax.swing.JTextField fn;
    private javax.swing.JComboBox<String> gn;
    private javax.swing.JTextField icn;
    private javax.swing.JComboBox<String> ill;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel timelab;
    // End of variables declaration//GEN-END:variables
}
